### ISSUE TITLE
Switch tooz driver backend

### ISSUE THREAD

**Issue by ricolin** [vexxhost/staffeln#111]
Currently tooz mysql driver requires pxc_strict_mode to MASTER.
As there are concerns, let's check on other tooz driver instead of mysql.

**Comment by ricolin** [comment]
as a log on this, I plan to make sure staffeln tooz driver support directly file that can be a PVC mounted across all staffeln services under Atmoshpere.

**Comment by okozachenko1203** [comment]
> as a log on this, I plan to make sure staffeln tooz driver support directly file that can be a PVC mounted across all staffeln services under Atmoshpere.

@ricolin but i wonder if that file should be shared across replicas and it means we need RWM PVC. Our current rbd SC doen't support RWM storageClass. And also it doesn't sound like a plan to use manila as a pre-requisite for stafflen.

**Comment by ricolin** [comment]
what we looking for is to have same share mounts for staffeln as  cinder-coordination to cinder 
That's to have a volume shared and mounts to all staffeln-conductor pods

ref1: https://github.com/vexxhost/atmosphere/blob/main/charts/cinder/templates/deployment-api.yaml#L187
ref2: https://github.com/vexxhost/atmosphere/blob/main/charts/cinder/templates/deployment-api.yaml#L72

**Comment by okozachenko1203** [comment]
> what we looking for is to have same share mounts for staffeln as cinder-coordination to cinder That's to have a volume shared and mounts to all staffeln-conductor pods
> 
> ref1: https://github.com/vexxhost/atmosphere/blob/main/charts/cinder/templates/deployment-api.yaml#L187 ref2: https://github.com/vexxhost/atmosphere/blob/main/charts/cinder/templates/deployment-api.yaml#L72

we should not ref that because that cinder coordination stuff doesn't work perfectly in the current osh implementation because they don't have shared volume

**Comment by ricolin** [comment]
@okozachenko1203 let's move the discuss for chart builds to https://github.com/vexxhost/staffeln/issues/107 :)
