### ISSUE TITLE
[Function]: Customize Horizon UI, c-bak panel

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/staffeln#23]

**Comment by okozachenko1203** [comment]
https://review.opendev.org/c/openstack/horizon/+/791532

**Comment by mnaser** [comment]
@okozachenko1203 looks like it's got -1 a while back, let's try and address those fixes upstream.

**Comment by okozachenko1203** [comment]
duplicated https://github.com/vexxhost/system-config/issues/157
